apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bg.name" . }}-blue
  labels:
    app.kubernetes.io/name: {{ .Values.labels.app }}
    color: blue
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.labels.app }}
      color: blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.labels.app }}
        color: blue
    spec:
      containers:
      - name: app
        image: "{{ .Values.app.imageBlue }}"
        ports:
          - containerPort: {{ .Values.app.containerPort }}
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://{{ include \"bg.name\" . }}-db-0.{{ include \"bg.name\" . }}-db-svc.default.svc.cluster.local:5432/{{ .Values.db.postgresDatabase }}"
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "bg.name" . }}-db-secret
                key: POSTGRES_USER
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "bg.name" . }}-db-secret
                key: POSTGRES_PASSWORD
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.app.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: {{ .Values.app.containerPort }}
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
{{ toYaml .Values.app.resources | indent 10 }}
